version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: quick-saas-backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src  # Sync local changes to the container for development

  init-ssl:
    image: alpine
    container_name: ssl-init
    command: >
      sh -c "
        apk add --no-cache openssl &&
        mkdir -p /etc/ssl &&
        openssl req -x509 -nodes -days 365 -newkey rsa:4096
        -keyout /etc/ssl/key.pem -out /etc/ssl/cert.pem -subj '/CN=localhost'
      "
    volumes:
      - ssl-certs:/etc/ssl
    # Ensure init completes before starting nginx
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: quick-saas-nginx
    ports:
      - "443:443"
    volumes:
      - ssl-certs:/etc/ssl  # Use generated SSL certificates
      - ./nginx.conf:/etc/nginx/nginx.conf  # Use custom Nginx configuration
    depends_on:
      - backend
      - init-ssl

  db:
    image: postgres:13
    container_name: quick-saas-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data in a named volume

volumes:
  ssl-certs:
  postgres_data:
