name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Configure SSL Certificates
      run: |
        # Update CA certificates
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        sudo update-ca-certificates
        # Configure npm to use secure connection
        npm config set registry https://registry.npmjs.org/
        npm config set strict-ssl true
        # Configure pip to use secure connection
        python -m pip install --upgrade pip
        pip install certifi
        
    - name: Install dependencies
      run: |
        # Install Python dependencies with proper SSL verification
        pip install -r requirements.txt
        # Install Node.js dependencies with proper SSL verification
        npm config set registry https://registry.npmjs.org/
        npm ci
        
    - name: Run tests
      run: |
        python -m pytest tests/
        npm test

    - name: Build
      run: |
        npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: dist
        retention-days: 5